# Generated by Django 4.1.13 on 2026-03-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="experimentmetric",
            new_name="plat_exp_me_run_id_eca1bd_idx",
            old_name="platform_ap_run_id_3c6bb9_idx",
        ),
        migrations.AlterModelTable(
            name="experimentmetric",
            table="plat_exp_metric",
        ),
        migrations.AlterModelTable(
            name="experimentrun",
            table="plat_exp_run",
        ),
    ]
