# Generated by Django 4.1.13 on 2026-03-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0002_rename_tables"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experimentrun",
            old_name="parent_run",
            new_name="parent",
        ),
    ]
